package eu.hohenegger.wickedbash;

import java.util.HashMap;
import java.util.Map;
import java.util.Properties;

import net.sf.wickedshell.facade.descriptor.environment.CmdShellEnvironmentalValueProvider;

public class GitBashEnvironmentalValueProvider extends CmdShellEnvironmentalValueProvider {

	private final Map<String, String> gitCommands = new HashMap<String, String>() {{
      put("git push", "");
	  put("git add", "");
	  put("git add--interactive", "");
	  put("git am", "");
	  put("git annotate", "");
	  put("git apply", "");
	  put("git archimport", "");
	  put("git archive", "");
	  put("git bisect", "");
	  put("git bisect--helper", "");
	  put("git blame", "");
	  put("git branch", "");
	  put("git bundle", "");
	  put("git cat-file", "");
	  put("git check-attr", "");
	  put("git check-ref-format", "");
	  put("git checkout", "");
	  put("git checkout-index", "");
	  put("git cherry", "");
	  put("git cherry-pick", "");
	  put("git citool", "");
	  put("git clean", "");
	  put("git clone", "");
	  put("git commit", "");
	  put("git commit-tree", "");
	  put("git config", "");
	  put("git count-objects", "");
	  put("git cvsexportcommit", "");
	  put("git cvsimport", "");
	  put("git cvsserver", "");
	  put("git daemon", "");
	  put("git describe", "");
	  put("git diff", "");
	  put("git diff-files", "");
	  put("git diff-index", "");
	  put("git diff-tree", "");
	  put("git difftool", "");
	  put("git difftool--helper", "");
	  put("git fast-export", "");
	  put("git fast-import", "");
	  put("git fetch", "");
	  put("git fetch-pack", "");
	  put("git filter-branch", "");
	  put("git fmt-merge-msg", "");
	  put("git for-each-ref", "");
	  put("git format-patch", "");
	  put("git fsck", "");
	  put("git fsck-objects", "");
	  put("git gc", "");
	  put("git get-tar-commit-id", "");
	  put("git grep", "");
	  put("git gui", "");
	  put("git gui--askpass", "");
	  put("git hash-object", "");
	  put("git help", "");
	  put("git http-backend", "");
	  put("git http-fetch", "");
	  put("git http-push", "");
	  put("git imap-send", "");
	  put("git index-pack", "");
	  put("git init", "");
	  put("git init-db", "");
	  put("git instaweb", "");
	  put("git log", "");
	  put("git lost-found", "");
	  put("git ls-files", "");
	  put("git ls-remote", "");
	  put("git ls-tree", "");
	  put("git mailinfo", "");
	  put("git mailsplit", "");
	  put("git merge", "");
	  put("git merge-base", "");
	  put("git merge-file", "");
	  put("git merge-index", "");
	  put("git merge-octopus", "");
	  put("git merge-one-file", "");
	  put("git merge-ours", "");
	  put("git merge-recursive", "");
	  put("git merge-resolve", "");
	  put("git merge-subtree", "");
	  put("git merge-tree", "");
	  put("git mergetool", "");
	  put("git mktag", "");
	  put("git mktree", "");
	  put("git mv", "");
	  put("git name-rev", "");
	  put("git notes", "");
	  put("git pack-objects", "");
	  put("git pack-redundant", "");
	  put("git pack-refs", "");
	  put("git patch-id", "");
	  put("git peek-remote", "");
	  put("git prune", "");
	  put("git prune-packed", "");
	  put("git pull", "");
	  put("git push", "");
	  put("git quiltimport", "");
	  put("git read-tree", "");
	  put("git rebase", "");
	  put("git receive-pack", "");
	  put("git reflog", "");
	  put("git relink", "");
	  put("git remote", "");
	  put("git remote-ext", "");
	  put("git remote-fd", "");
	  put("git remote-ftp", "");
	  put("git remote-ftps", "");
	  put("git remote-http", "");
	  put("git remote-https", "");
	  put("git remote-testgit", "");
	  put("git repack", "");
	  put("git replace", "");
	  put("git repo-config", "");
	  put("git request-pull", "");
	  put("git rerere", "");
	  put("git reset", "");
	  put("git rev-list", "");
	  put("git rev-parse", "");
	  put("git revert", "");
	  put("git rm", "");
	  put("git send-email", "");
	  put("git send-pack", "");
	  put("git sh-i18n--envsubst", "");
	  put("git shell", "");
	  put("git shortlog", "");
	  put("git show", "");
	  put("git show-branch", "");
	  put("git show-index", "");
	  put("git show-ref", "");
	  put("git stage", "");
	  put("git stash", "");
	  put("git status", "");
	  put("git stripspace", "");
	  put("git submodule", "");
	  put("git svn", "");
	  put("git symbolic-ref", "");
	  put("git tag", "");
	  put("git tar-tree", "");
	  put("git unpack-file", "");
	  put("git unpack-objects", "");
	  put("git update-index", "");
	  put("git update-ref", "");
	  put("git update-server-info", "");
	  put("git upload-archive", "");
	  put("git upload-pack", "");
	  put("git var", "");
	  put("git verify-pack", "");
	  put("git verify-tag", "");
	  put("git web--browse", "");
	  put("git whatchanged", "");
	  put("git write-tree", "");
	}};

	@Override
	public Properties getEnviromentalValues() {
		Properties enviromentalValues = super.getEnviromentalValues();

		enviromentalValues.putAll(gitCommands);

		return enviromentalValues;
	}

}
